<?php

return [
    'show_warnings' => false,
    'orientation' => 'portrait',
    'defines' => [
        'font_dir' => storage_path('fonts'),
        'font_cache' => storage_path('fonts'),
        'temp_dir' => sys_get_temp_dir(),
        'chroot' => realpath(base_path()),
        'enable_font_subsetting' => false,
        'enable_remote' => false,
        'allowedRemoteHosts' => null,
        'log_output_file' => null,
        'enable_html5_parser' => true,
        'default_paper_size' => 'a4',
        'default_paper_orientation' => 'portrait',
        'default_font' => 'DejaVu Sans',
        'dpi' => 96,
        'enable_php' => false,
        'enable_javascript' => false,
        'enable_css_float' => true,
        'font_height_ratio' => 1.1,
        'is_php_enabled' => false,
        'is_remote_enabled' => false,
        'is_javascript_enabled' => false,
        'is_html5_parser_enabled' => true,
        'is_font_subsetting_enabled' => false,
        'isFontSubsettingEnabled' => false,
    ],
];
